name: Build LaTeX Document

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      run: |
        docker run --rm -v ${{ github.workspace }}:/workdir texlive/texlive /bin/bash -c "
          pdflatex -interaction=nonstopmode -file-line-error resume.tex && \
          pdflatex -interaction=nonstopmode -file-line-error resume.tex && \
          rm -f *.log *.aux *.out
        "
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ali-khajezade-resume.pdf
        path: resume.pdf
