name: Build LaTeX Document

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile LaTeX document
      run: |
	docker run --rm -v ${{ github.workspace }}:/workdir texlive/texlive pdflatex resume.tex
	docker run --rm -v ${{ github.workspace }}:/workdir texlive/texlive /bin/bash -c "
          rm -f *.log *.aux *.out
	"

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: ali-khajezade-resume.pdf
        path: ali-khajezade-resume.pdf
