name: Build LaTeX Document

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile LaTeX document
      run: docker run --rm -v ${{ github.workspace }}:/workdir blang/latex pdflatex resume.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: ali-khajezade-resume.pdf
        path: main.pdf
