name: Build LaTeX Document

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install package dependencies
      run: |
        docker run --rm -v ${{ github.workspace }}:/workdir blang/latex tlmgr update --self
        docker run --rm -v ${{ github.workspace }}:/workdir blang/latex tlmgr install \
          fontawesome5 \
          latexsym \
          fullpage \
          titlesec \
          marvosym \
          xcolor \
          verbatim \
          enumitem \
          hyperref \
          fancyhdr \
          babel-english \
          tabularx

    - name: Compile LaTeX document
      run: docker run --rm -v ${{ github.workspace }}:/workdir blang/latex pdflatex ./resume.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: ali-khajezade-resume.pdf
        path: ali-khajezade-resume.pdf
